### PR TITLE
CIWEMB-289: Allow credit_note status field to be null

### PR DESCRIPTION
**Pull request by olayiwola-compucorp**
## Overview
This PR allows the credit_note to be nullable, such that the status becomes an optional field when its create API action is called.

## Before
The status field must be passed when creating a new credit_note entity.

## After
The status field for a credit note entity create API action is optional.

### CODE REVIEW

**Review by omarabuhussein — COMMENTED** [review]
what is the purpose of this change ? I cannot find a relevant discussion in the ticket, shouldn't the credit note always be in certain state ?

**Comment by olayiwola-compucorp** [comment]
Hi, @omarabuhussein as mentioned in the description 

> such that the status becomes an optional field when its create API action is called.

The status field is not set by the user; instead, it is set when it is set from the backend. if the status field is not optional and its create API is called API4 will throw an error.

**Comment by omarabuhussein** [comment]
@olayiwola-compucorp I just assume all credit notes created on the system should by default have the "Open" status, it is just my assumption given I cannot see anywhere on the specs talking about that, so I just left a comment there about it for Jamie.

**Comment by jamienovick** [comment]
@pallavi-compuco can we update the spec:
- The status is required yes, should be an option list so users can modify it and open should be the default value when we ship. Thanks
@omarabuhussein good spot!

**Comment by pallavi-compuco** [comment]
Left a comment @jamienovick for you to check once

**Pull request closed without merging**
